server:
    port: 8084
zuul:
  routes:
  # 将　Oauth Server (8081端口) 的所有服务映射到本服务的URL路径　/oauth/**
    oauth:
      path: /oauth/**
      url: http://localhost:8081/spring-security-oauth-server/oauth
  Servlet30WrapperFilter:
    pre:
      disable:true

# 当前系统所使用的 Auth client 的信息
client :
      id : fooClientIdPassword
      secret : secret

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG